name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: build
    runs-on: [self-hosted, server-runner]  # <--- your server label
    steps:
      - name: Show runner info
        run: |
          hostname
          ip addr show

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove old container
        run: |
          docker stop flask-app || true
          docker rm flask-app || true

      - name: Build and run Docker container
        run: |
          docker build -t flask-app:latest .
          docker run -d --name flask-app -p 5000:5000 flask-app:latest

      - name: Cleanup unused images
        run: docker system prune -f
