name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # Run on your self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover

  deploy:
    needs: build
    runs-on: self-hosted  # Run deploy on your runner too
    steps:
      - name: Show runner info
        run: |
          hostname
          ip addr show
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-app:latest .
      - name: Check connectivity
        run: ping -c 3 ${{ secrets.SSH_HOST }}


      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set +e  # allow non-zero exit codes without failing the job
            docker stop flask-app || true
            docker rm flask-app || true
            set -e  # turn error checking back on
            docker build -t flask-app:latest
            docker run -d --name flask-app -p 5000:5000 flask-app:latest


